### ISSUE TITLE
데이터베이스 접근 계정 비공개 방안 고민

### ISSUE THREAD

**Issue by skyoo2003** [teamyy/gotcha#21]
- settings.py 에 디비에 접속 가능한 계정이 노출되는게 이상한 듯.
- 접근 계정을 노출하지 않고, 해결할 수 있는 방안이 있을지 고민해보자!

**Comment by skyoo2003** [comment]
계정은 그대로 유지하되, 디비를 localhost 에서만 엑세스 가능하게 권한을 제어하면 될까염?

**Comment by yyh910214** [comment]
권한 제어로 막을 수 있을것 같긴 하지만 그래도 계정정보가 노출되는게 꺼림칙하긴 하네요.. ㅎㅎ 고려해보져

**Comment by yyh910214** [comment]
https://github.com/AGWA/git-crypt 최소한 git으로 관리할때는 이거라도 사용해볼까요?ㅎㅎ

**Comment by skyoo2003** [comment]
파일을 암호화하는건가염?

**Comment by yyh910214** [comment]
넵 ㅎㅎ 중요 정보들 관련된 파일을 따로 빼서 암호화 대상으로 지정해놓으면 될거같아여.
우리 둘다 keyfile만 공유하면 될듯

**Comment by skyoo2003** [comment]
settings.py 전체를 암호화하는 것보다는 디비 접근관련 정보만 분리할 수 있을까여?

**Comment by yyh910214** [comment]
음.. 그냥 db정보를 따로 저장해놓고 해당 파일을 읽어서 db커넥션을 만들도록 하면 가능은 할 것 같아요. settings에서 읽어오지 않고ㅎㅎ 
뭔가 깔끔하진 않겠네요. settings.py를 분리해서 관리할 수 있는 방법이 있나 찾아봤는데 없는것 같아서요

**Comment by skyoo2003** [comment]
디비 서버에서 접근 가능한 IP 리스트를 정의해서 허용된 호스트의 접속만 허용하는 방식이 맞는 것 같아요.
- 방화벽이나, 디비에서 가능한 호스트의 계정만 만드는 방법!

**Comment by skyoo2003** [comment]
디비 접속 권한을 localhost로 제한하였습니다.
추후에 크롤러 서버가 2개 이상으로 증가하는 경우, 내부 IP로 접근 가능한 계정을 생성하고 해당 계정의 접근을 통해 해결하도록 하겠습니다.
