### ISSUE TITLE
이미 방문한 url은 일정 주기를 두고 다시방문할 수 있도록 해보자

### ISSUE THREAD

**Issue by yyh910214** [teamyy/gotcha#32]
같은 사이트에서 링크를 수집하다 보면 계속해서 중복되는 url이 수집될텐데,
이미 방문한 url을 별도로 관리해서 재방문 주기를 설정할 수 있도록 해보자.

**Comment by skyoo2003** [comment]
더불어서 중복 URL 처리하는게 필요할 것 같아염.
파라미터가 조금 다른 경우에도 랜딩 문서는 동일한 경우가 있네여.

웃긴대학인가 뽐뿌에서 크롤러의 UserAgent 를 보고 파라미터를 기계적으로 붙여주는 경우가 있더라구요.
device=pc 같은 파라미터가 있는 경우와 없는 경우가 중복으로 수집되네여

같은 이슈로 처리되기 어렵다면, 다른 이슈로 발급해서 진행해도 되겠네요

**Comment by skyoo2003** [comment]
https://github.com/teamyy/gotcha/issues/22
위의 이슈와 공통점이 있는 것 같아서 같이 이슈처리 진행해도 될듯해염
